In [6]:
import torch
import torch.nn.init as tini
A = torch.Tensor([[0,1,3],[2,1,0],[1,1,1],[1,2,3]])
B = torch.Tensor([[2,4,5],[1,2,3],[4,5,1],[2,3,4]])
print(A*A)
print(torch.sum(A*A,dim=2).size())
ti.xavier_normal_(torch.ones((10,2)))

tensor([[[0., 1.],
         [4., 0.]],

        [[1., 1.],
         [4., 9.]]])
torch.Size([2, 2])


tensor([[-0.9599,  0.2180],
        [-0.2727,  0.5368],
        [-0.1912,  0.1746],
        [-0.6520,  0.0243],
        [-0.8446, -0.4968],
        [-0.1694,  0.0801],
        [-0.6207,  0.6188],
        [-0.2024,  0.0454],
        [-0.0652, -0.2198],
        [ 0.1910,  0.1114]])

In [11]:
ref_id = 0
tgt_list = list(range(16))
tgt_list.pop(ref_id)
tgt_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [7]:
import torch
A = torch.Tensor([[1,0,0],[0,0,2]])
B = torch.Tensor([[1,0,0],[0,0,1]])
#C = torch.cat((A.unsqueeze(0),B.unsqueeze(0)),dim=0).contiguous()
#print(C,torch.__version__)
torch.cdist(A,B)

tensor([[0.0000, 1.4142],
        [2.2361, 1.0000]])

In [8]:
pow(2,1/2)

1.4142135623730951